In [1]:
!pip install transformers
!pip install datasets
!pip install torch
!pip install soundfile
!pip install librosa
from transformers import AutoFeatureExtractor, HubertForSequenceClassification
from datasets import load_dataset
import torch
import torch.nn.functional as F

In [2]:
ds_train = load_dataset("audiofolder", data_dir="/teamspace/studios/this_studio/dataset")


Resolving data files:   0%|          | 0/30240 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/12960 [00:00<?, ?it/s]

In [8]:
sampling_rate = ds_train['train'][0]['audio']['sampling_rate']
# sampling_rate = dataset.features["audio"].sampling_rate

In [9]:
feature_extractor = AutoFeatureExtractor.from_pretrained("ntu-spml/distilhubert")

In [7]:
ds_train['train'][0]['audio']['sampling_rate']

16000

In [10]:
inputs = feature_extractor(
        ds_train['train'][0]['audio']['array'],
        sampling_rate=sampling_rate,
        return_tensors="pt"
    )

In [11]:
inputs

{'input_values': tensor([[0.0000, 0.0000, 0.0000,  ..., 0.0007, 0.0006, 0.0007]])}

In [88]:
# Crear una lista para almacenar los tensores procesados
all_inputs = []

# Iterar sobre todas las posiciones (asumiendo que ds_train['train'] tiene 30240 elementos)
for i in range(1000):
    # Extraer las características de la muestra actual
    inputs = feature_extractor(
        ds_train['train'][i]['audio']['array'],
        sampling_rate=sampling_rate,
        return_tensors="pt"
    )
    # Agregar el tensor procesado a la lista
    all_inputs.append(inputs['input_values'])  # Ajusta esto según la estructura de salida de tu feature_extractor

inputs = torch.cat(all_inputs, dim=0)

In [89]:
all_inputs

[tensor([[0.0000, 0.0000, 0.0000,  ..., 0.0007, 0.0006, 0.0007]]),
 tensor([[0.0000, 0.0000, 0.0000,  ..., 0.0005, 0.0005, 0.0007]]),
 tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -3.0518e-05,
           0.0000e+00,  6.1035e-05]]),
 tensor([[ 0.0000,  0.0000,  0.0000,  ...,  0.0001,  0.0000, -0.0002]]),
 tensor([[ 0.0000,  0.0000,  0.0000,  ..., -0.0009, -0.0008, -0.0009]]),
 tensor([[0.0000, 0.0000, 0.0000,  ..., 0.0002, 0.0003, 0.0005]]),
 tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -3.0518e-05,
          -6.1035e-05, -1.8311e-04]]),
 tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -9.1553e-05,
          -1.2207e-04, -1.8311e-04]]),
 tensor([[ 0.0000,  0.0000,  0.0000,  ..., -0.0009, -0.0009, -0.0010]]),
 tensor([[0.0000, 0.0000, 0.0000,  ..., 0.0004, 0.0004, 0.0006]]),
 tensor([[0.0000, 0.0000, 0.0000,  ..., 0.0016, 0.0016, 0.0015]]),
 tensor([[ 0.0000,  0.0000,  0.0000,  ..., -0.0003, -0.0005, -0.0006]]),
 tensor([[0.0000, 0.0000, 0.0000,  ..., 0.0008, 0.00

In [6]:
# max_duration = 4.0
# def preprocess_function(examples):
#     audio_arrays = [x["array"] for x in examples["audio"]]
#     inputs = feature_extractor(
#         audio_arrays,
#         sampling_rate=sampling_rate,
#         return_tensors="pt"
#     )
#     return inputs

In [164]:
# ds_train['train'][0]['audio']['array']

array([ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
       -3.05175781e-05,  9.15527344e-05,  2.44140625e-04])

In [9]:
# a = preprocess_function(ds_train['train']['audio'][0]['array'])

In [129]:
# len(a['input_values'])

4

In [124]:
# len(a['input_values'][0])

64000

In [98]:
# ds_train_encode = ds_train.map(
#     preprocess_function,
#     remove_columns=["audio", "label"],
#     batched=True,
#     batch_size=100,
#     num_proc=1,
# )
# ds_train_encode

DatasetDict({
    train: Dataset({
        features: ['input_values', 'attention_mask'],
        num_rows: 4
    })
    test: Dataset({
        features: ['input_values', 'attention_mask'],
        num_rows: 2
    })
})

In [113]:
# inputs

{'input_values': tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -3.0518e-05,
          9.1553e-05,  2.4414e-04]])}

In [103]:
# input_values

array([[ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
        -3.0517578e-05,  9.1552734e-05,  2.4414062e-04]], dtype=float32)

In [97]:
# ds_train_encode['train']

Dataset({
    features: ['input_values', 'attention_mask'],
    num_rows: 4
})

In [48]:
# input_values = ds_train_encode['train']['input_values']

In [20]:
# len(input_values[0])

64000

In [14]:
from transformers import Wav2Vec2Processor, Wav2Vec2Model, Wav2Vec2FeatureExtractor

# Cargar el modelo y el procesador de DistilHuBERT
#processor = Wav2Vec2FeatureExtractor.from_pretrained("ntu-spml/distilhubert")
model = Wav2Vec2Model.from_pretrained("ntu-spml/distilhubert")

# Suponiendo que ds_train['train'][0]["audio"]["array"] contiene tu audio y sampling_rate es la tasa de muestreo
# inputs = processor(ds_train['train'][0]["audio"]["array"], sampling_rate=sampling_rate, return_tensors="pt")

# # Extraer características
# with torch.no_grad():
#     features = model(inputs.input_values).last_hidden_state

# print(features.shape)  # Verificar la forma de las características extraídas


You are using a model of type hubert to instantiate a model of type wav2vec2. This is not supported for all configurations of models and can yield errors.
Some weights of Wav2Vec2Model were not initialized from the model checkpoint at ntu-spml/distilhubert and are newly initialized: ['encoder.pos_conv_embed.conv.parametrizations.weight.original0', 'encoder.pos_conv_embed.conv.parametrizations.weight.original1', 'feature_projection.layer_norm.bias', 'feature_projection.layer_norm.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [52]:
# input_values

tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -3.0518e-05,
          9.1553e-05,  2.4414e-04]])

In [94]:
from torch.nn.utils.rnn import pad_sequence
padded_inputs = pad_sequence(all_inputs, batch_first=True)
padded_inputs = padded_inputs.squeeze(1) 

with torch.no_grad():
    features = model(padded_inputs).last_hidden_state

RuntimeError: [enforce fail at alloc_cpu.cpp:117] err == 0. DefaultCPUAllocator: can't allocate memory: you tried to allocate 26212352000 bytes. Error code 12 (Cannot allocate memory)

In [45]:
# len(ds_train_encode['train']['input_values'][0])

64000

In [77]:
features.shape

torch.Size([10, 199, 768])

In [131]:
# pooled_features = F.avg_pool1d(features.permute(0, 2, 1), kernel_size=4).permute(0, 2, 1)

In [78]:
pooled_features_max, _ = torch.max(features, dim=1)

In [86]:
pooled_features_max.shape

torch.Size([10, 768])

In [27]:
# len(pooled_features[0][0])

768

In [87]:
len(pooled_features_max)

10